title: Hassan Ishtiaq's Homepage
page-top-title: Hassan Ishtiaq Minhas
top-section-bg-text: Be what you wanna be
home-subtitle: Hassan Ishtiaq Minhas
copyright-text: '&copy; Hassan Ishtiaq 2017-2026. All Rights Reserved. Last Updated: Jun 2026.'
